#!/bin/bash

action_type=$1
from_uuid=$2
shift 2

from_type=$(cat $data_dir/robots/$from_uuid/type)

function result ()
{
    send $uuid result $action_type $from_uuid $*
}

function read_property ()
{
    if [[ -f $scripts_dir/actions/$action_type/$1 ]]
    then
        source $scripts_dir/actions/$action_type/$1
    elif [[ -f $scripts_dir/actions/$action_type/${1}s/$from_type ]]
    then
        source $scripts_dir/actions/$action_type/${1}s/$from_type
    else
        let "$1=$2"
    fi
}

function source_check ()
{
    if [[ -f $scripts_dir/actions/$action_type/check ]]
    then
        source $scripts_dir/actions/$action_type/check
        return $?
    else
        return 0
    fi
}

if [[ -e $scripts_dir/actions/$action_type/allowed_types/$from_type ]]
then
    if source_check $*
    then
        {
            read_property cost 0
            echo $action_type > $data_dir/robots/$from_uuid/status
            sleep $cost
            source $scripts_dir/actions/$action_type/script
            echo idle > $data_dir/robots/$from_uuid/status
        } &
    fi
else
    result 'failure no such action for your type'
fi
