#!/bin/bash

robot_type=$1

{
    if [[ $robot_type != headquarters ]]
    then
        sleep 2
    fi

    tmpfile=$(mktemp)

    cd robots
    while read robot_uuid
    do
        cd $robot_uuid
        {
            printf '{"type":"%s",' $(cat type)
            printf '"x":"%s",' $(cat position/x)
            printf '"y":"%s",' $(cat position/y)
            printf '"uuid":"%s"},' $robot_uuid
        } >> $tmpfile
        cd ..
    done < <(ls -1)

    result "success [$(cat $tmpfile | sed s/.$//)]"
    rm $tmpfile
} &
