#!/bin/bash

robot_type=$1

{
    if [[ $robot_type != headquarters ]]
    then
        sleep 2
    fi

    cd robots
    while read robot_uuid
    do
        cd $robot_uuid
        new=$({
            printf '{"type":"%s",' $(cat type)
            printf '"x":"%s",' $(cat position/x)
            printf '"y":"%s",' $(cat position/y)
            printf '"uuid":"%s"}' $robot_uuid
        })
        if [[ $results ]]
        then
            results="$results,$new"
        else
            results="$new"
        fi
        cd ..
    done < <(ls -1)

    result "success [$results]"
} &
