#!/bin/bash

target_uuid=$1

if [[ $(cat $data_dir/robots/$target_uuid/status) != off ]]
then
    result failure 'target robot not off'
    return 1
fi

read_property range
robot_distance $from_uuid $target_uuid

if [[ ! $distance -le $range ]]
then
    result failure 'target robot too far away'
    return 1
fi

return 0
