#!/bin/bash

target_uuid=$1

from_x=$(cat $data_dir/robots/$from_uuid/position/x)
from_y=$(cat $data_dir/robots/$from_uuid/position/y)

target_x=$(cat $data_dir/robots/$target_uuid/position/x)
target_y=$(cat $data_dir/robots/$target_uuid/position/y)

offset_x=$(($from_x - $target_x))
offset_y=$(($from_y - $target_y))

if [[ $(abs $offset_x) -lt 6 && $(abs $offset_y) -lt 6 ]]
then
    {
        sleep 10

        send $uuid start $target_uuid
        result success
    } &
else
    result failure 'target robot too far away'
fi
