#!/bin/bash

target_uuid=$1
from_uuid=$2
supervisor_uuid=$3

cd robots/$from_uuid/results
if [[ $supervisor_uuid == $my_id ]]
then
    echo success $data_dir/robots/$target_uuid/drive/ > $uuid
else
    out 'Not yet implemented: mount ftp server'
    echo failure not yet implemented > $uuid
fi
