#!/bin/bash

robot_type=$1

pos_x=$2
pos_y=$3

if [[ ! -f $scripts_dir/actions/spawn/type_table/$from_type/$robot_type ]]
then
    result failure 'you may not spawn that type of robot'
    return 1
fi

if [[ $pos_x && $pos_y ]]
then
    read_property range
    distance $pos_x $pos_y $(cat $data_dir/robots/$from_uuid/position/{x,y})
    if [[ ! $distance -le $range ]]
    then
        result failure 'the new position is too far away'
        return 1
    fi
    if [[ -f $data_dir/position_map/$pos_x:$pos_y ]]
    then
        result failure 'the new position is occupied'
        return 1
    fi
fi
