#!/bin/bash

factory_uuid=$from_uuid

if [[ $pos_x && $pos_y ]]
then
    source_script scripts/spawn_robot.sh $robot_type $pos_x $pos_y
else
    source_script scripts/spawn_robot.sh $robot_type $range
fi

result success $robot_uuid
