#!/bin/bash

port=2005

function main ()
{
    >&2 echo A lua shell is available on port $port
    while true
    do
        mkfifo actions results
        cat < actions &
        cat > results &
        ncat --listen $port --sh-exec "lua -v -i 2>&1"
        rm actions results
        while read process_id
        do
            kill $process_id
        done < <(jobs -r -p)
    done 2>/dev/null
}

main
