#!/bin/bash

port=2005

function main ()
{
    mkfifo actions results
    cat < actions &
    cat > results &

    >&2 echo A lua shell is available on port $port
    ncat --keep-open --listen $port --sh-exec "lua -v -i 2>&1"
}

main
