#!/bin/bash

cd robots/$from_uuid/

result success $({
    printf '{"type":"%s",' $(cat type)
    printf '"x":"%s",' $(cat position/x)
    printf '"y":"%s",' $(cat position/y)
    printf '"uuid":"%s"}' $robot_uuid
})
