#!/bin/bash

target_uuid=$1

{
    sleep $cost

    read_property range

    robot_distance $from_uuid $target_uuid
    if [[ $distance -le $range ]]
    then
        target_supervisor=$(cat $data_dir/robots/$target_uuid/supervisor)
        if [[ $target_supervisor != $supervisor_uuid ]]
        then
            cd $data_dir/message_queues/$target_supervisor/
            echo $uuid open_ftp $target_uuid $supervisor_uuid > $uuid
        fi
        send $uuid access $target_uuid $from_uuid $target_supervisor
    else
        result failure 'target robot too far away'
    fi
} &
